import { Router } from "express";
import { routesAuth } from "../modules/auth/auth.routes";
import { routesPrestataires } from "../modules/prestataires/prestataires.routes";
import { routesServices } from "../modules/services/services.routes";
import { routesReservations } from "../modules/reservations/reservations.routes";
import { routesPaiements } from "../modules/paiements/paiements.routes";
import { routesAvis } from "../modules/avis/avis.routes";
import { routesNotifications } from "../modules/notifications/notifications.routes";
import { routesAdmin } from "../modules/admin/admin.routes";
import { routesFavoris } from "../modules/favoris/favoris.routes";
import { routesPublicites } from "../modules/publicites/publicites.routes";
import { routesChat } from "../modules/chat/chat.routes";
import { routesUpload } from "../modules/upload/upload.routes";
import { routesCodesPromos } from "../modules/codes-promos/codes-promos.routes";
import { routesFidelite } from "../modules/fidelite/fidelite.routes";
import { routesCartesCadeaux } from "../modules/cartes-cadeaux/cartes-cadeaux.routes";
import { routesPackages } from "../modules/packages/packages.routes";
import { routesAvoirs } from "../modules/avoirs/avoirs.routes";
import { routesAlertes } from "../modules/alertes/alertes.routes";
import { routesAttentes } from "../modules/attentes/attentes.routes";
import { routesIndisponibilites } from "../modules/indisponibilites/indisponibilites.routes";
import { routesPortefeuille } from "../modules/portefeuille/portefeuille.routes";
import { routesEconomie } from "../modules/economie/economie.routes";
import { routesInnovations } from "../modules/innovations/innovations.routes";

export const routesApi = Router();

routesApi.use("/auth", routesAuth);
routesApi.use("/prestataires", routesPrestataires);
routesApi.use("/services", routesServices);
routesApi.use("/reservations", routesReservations);
routesApi.use("/paiements", routesPaiements);
routesApi.use("/avis", routesAvis);
routesApi.use("/notifications", routesNotifications);
routesApi.use("/favoris", routesFavoris);
routesApi.use("/publicites", routesPublicites);
routesApi.use("/admin", routesAdmin);
routesApi.use("/chat", routesChat);
routesApi.use("/upload", routesUpload);
routesApi.use("/codes-promos", routesCodesPromos);
routesApi.use("/fidelite", routesFidelite);
routesApi.use("/cartes-cadeaux", routesCartesCadeaux);
routesApi.use("/packages", routesPackages);
routesApi.use("/avoirs", routesAvoirs);
routesApi.use("/alertes", routesAlertes);
routesApi.use("/attentes", routesAttentes);
routesApi.use("/indisponibilites", routesIndisponibilites);
routesApi.use("/portefeuille", routesPortefeuille);
routesApi.use("/economie", routesEconomie);
routesApi.use("/innovations", routesInnovations);
